apiVersion: v1
kind: Service
metadata:
  name: gestion-gimnacio-service
spec:
  type: NodePort
  selector:
    app: gestion-gimnacio
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30080